### PR TITLE
Networks (graphs with properties)

### LINKED ISSUE #7: read also edge and vertex maps from files

### PR DESCRIPTION
**Pull request by CarloLucibello**
Adds networks (graphs with the ability to store internally graph/vertex/edge properties). Defines an interface and  abstract and concrete types. Also implement the ability to write and read properties along with the graph for some file formats (fixes #7 ).

In redefining types and names (A)SimpleGraph has become (A)GraphOrDiGraph, which is much more explicative. 

- [x] type PropertyStore has a default handler for graph/vertex/edge properties
- [x] ANetwork, ADiNetwork abstract types inheriting from AGraph, ADiGraph
- [x] Define network interface (property accessors). Still some polishing TODO
- [x] GTGraph + PropertyStore -> Network
- [x] benchmark performance of Network. Found no signficative loss with respect to Graph
- [x] subgraph for networks should inherit the properties of the original network. Define `subnetwork`? yes
- [x] more tests 
- [x] more docs
- [ ] write/read properties with `writenetwork` and `readnetwork`
    - [x] .gt
    - [x] .graphml
    - [ ] .dot
    - [x] .gml
    - [ ] .gexf

### CODE REVIEW

**Comment by CarloLucibello** [comment]
>should delete these when finished

thanks, will do

**Comment by CarloLucibello** [comment]
> shouldn't be overwriting a Base method on Base types

I'm not really overwriting, I'm extending, `valtype` is not defined for arrays in Base. Is this ok?

In any case this is temporary, `VertexMap{T}` will be its own type at some point and not a `Union{Dict{Int, T}, Vector{T}}`

**Comment by tkelman** [comment]
It's not defined for arrays because arrays aren't associative containers, and valtype is only defined for associative containers. Do you need to extend `Base.valtype` or can you use a module-local version of it, `_valtype` or something?

**Comment by CarloLucibello** [comment]
I used valtype and not an internal method because to me a vertex map is an associative container which in some cases happens to be an array, since vertex are 1:n indexed. I don't want to mess with unrelated code anyway, better just define a VertexMap type and have an array as one of the possible underlying storage types. I'll file a PR in the next days and tag a new version

**Pull request merged**
